# Simple factories for testing stuff.
FactoryGirl.define do
  factory :plan do
    title 'The title of a FactoryGirl test plan.'
    description 'This is a test plan generated by FactoryGirl.'
    due_date "12-25-2012"
    completed false
  end

  factory :task do
    description 'A task generated by FactoryGirl that is part of a plan. It is not completed.'
    association :plan
    completed false
  end

  factory :user do
    email "example@example.com"
    password "password"
    user_name "Foo Bar"
  end

end
